config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # ActiveAdmin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  # Website routes
  filter :locale, :exclude => /^\/admin/

  # Defines the root path route ("/")
  root "articles#index"

  get 'news', to: 'articles#news_category', as: :news_category
  get 'articles', to: 'articles#articles_category', as: :articles_category
  resources :articles, only: [:index, :show] do
    collection do
      get :feed, to: 'articles#feed'
      get :search, to: 'articles#search'
      get :tags, to: 'articles#tags'
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_one :article_category, primary_key: :slug, foreign_key: :article_category_id
    has_and_belongs_to_many :tags

    scope :with_tag, ->(tag_id) { joins(:tags).where(tags: { id: tag_id }) }

    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "id", "id_value", "published_at", "title", "tldr"]
    end

    def self.ransackable_associations(auth_object = nil)
        ["article_category", "tags"]
    end
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    self.primary_key = 'slug'
    has_many :articles

    def self.ransackable_associations(auth_object = nil)
        ["articles"]
    end
    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "slug", "title", "updated_at"]
    end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :articles

    def self.ransackable_attributes(auth_object = nil)
        ["name"]
    end

    def self.ransackable_associations(auth_object = nil)
        ["articles"]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    around_action :switch_locale

    def switch_locale(&action)
        locale = params[:locale] || I18n.default_locale
        I18n.with_locale(locale, &action)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.page(params[:page]).per(12)
    # @feed_articles = feed
    # puts(@feed_articles)
  end

  def feed
    if params[:column].present?
      @feed_articles = get_category("news", nil, 25).order("#{params[:column]} #{params[:direction]}")
    else
      @feed_articles = get_category("news", nil, 25)
    end
    render partial: "feed"
  end

  def show
    @article = Article.find(params[:id])
  end

  def news_category
    @articles = get_category("news", :page, 5).order("published_at desc")
    @tags = Tag.all
  end

  def articles_category
    @articles = get_category("articles", :page, 5).order("published_at desc")
    @tags = Tag.all
  end

  def search
    @articles = Article.where("title LIKE ?", "%#{params[:query]}%")
    @count = @articles.count
    @articles = @articles.page(params[:page]).per(15)
    # @query = params[:query]
  end

  def tags
    if params[:tag].present?
      @articles = Article.with_tag(params[:tag]).page(params[:page]).per(15)
      @tags = Tag.all
      @tag = @tags.find_by(id: params[:tag])
      @tags = @tags.limit(15)
    else
      redirect_to articles_path
    end
  end

  private
  
  def get_category(slug, page, per)
    @category = ArticleCategory.find_by(slug: slug)
    @articles = @category.present? ? @category.articles.page(params[page]).per(per) : ArticleCategory.none
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def format_datetime(datetime)
        datetime = datetime + 5.hours
        if datetime.to_date == (DateTime.now - 24.hours).to_date
            datetime.strftime("Вчера %H:%M")
        elsif datetime.to_date == DateTime.now.to_date 
            datetime.strftime("Сегодня %H:%M")
        else
            datetime.strftime("%d %B %Y %H:%M")
        end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def sort_link(column:, label:, direction: "desc", active: false)
        link_to(label, feed_articles_path(column: column, direction: direction), data: { turbo_frame: "feed" }, class: "feed-link " + (active ? "active": ""))
    end
end

app/views/articles/_article_item.html.erb
<article>
    <a href="<%= article_path(article) %>">
        <picture>
            <img class="main-news_top_item_img" loading="lazy" src="<%= article.image_url %>">
        </picture>
    </a>
    <h4><%= link_to article.title, article %></h4>
    <p><%= article.tldr  %></p>
    <div>
        <span><%= format_datetime(article.published_at) %>&emsp;
        </span>
        <span class="no-break"><img src="https://tengrinews.kz/tengri_new/img/viewings.svg"> <%= article.views %></span>
        <%# Footer %>
    </div>
</article>

app/views/articles/_feed.html.erb
<%= turbo_frame_tag "feed" do %>
    <% @feed_articles.each do |feed_article| %>
        <article>
            <%= link_to feed_article.title, article_path(feed_article), data: {turbo_frame: "_top"} %>
            <div class="footer">
                <span><%= format_datetime(feed_article.published_at) %></span>
                <span class="right no-break">
                    <img src="https://tengrinews.kz/tengri_new/img/viewings.svg">
                    Views <%= feed_article.views %>
                </span>
            </div>
        </article>
    <% end %>
<% end %>
<%# latest / popular news %>

app/views/articles/_searchbox.html.erb
<%= form_with(url: search_articles_path, method: "get", id: "search-form") do %>
    <%= text_field_tag :query, params[:query], placeholder: "Найти в TengriNews Олжаса", :required => true %>
    <%= submit_tag "Поиск" %>
<% end %>

app/views/articles/_tags_list.html.erb
<div class="tags">
    <% @tags.each do |tag| %>
        <%= link_to tag.name, tags_articles_path(tag:tag.id) %>
    <% end %>
</div>

app/views/articles/articles_category.html.erb
<% content_for :articles_header do %>
    <div class="breadcrumb">
        <%= link_to "Главная |", "/" %> <%= @category.title %>
    </div>
    <h1><%= @category.title %></h1>
    <hr class="green"><hr class="gray">
<% end %>
<% content_for :articles_content do %>
    <div id="articles-list">
        <% @articles.each do |article| %>
            <%= render 'article_item', article: article %>
        <% end %>
    </div>
    <div class="pagination">
        <%= paginate @articles %>
    </div>
<% end %>

app/views/articles/index.html.erb
<div id="featured-list">
    <% @articles.each do |article| %>
        <article>
            <a href="<%= article_path(article) %>">
                <picture>
                    <img class="main-news_top_item_img" loading="lazy" src="<%= article.image_url %>">
                </picture>
            </a>
            <h5> <%= link_to article.title, article %></h5>
            <div>
                <span><%= format_datetime(article.published_at) %>&emsp;
                </span>
                <span class="no-break"><img src="https://tengrinews.kz/tengri_new/img/viewings.svg"> <%= article.views %></span>
                <%# Footer %>
            </div>
        </article>
    <% end %>
</div>
<div class="pagination">
    <%= paginate @articles %>
</div>

app/views/articles/news_category.html.erb
<% content_for :articles_header do %>
    <div class="breadcrumb">
        <%= link_to "Главная |", "/" %> <%= @category.title %>
    </div>
    <div class="title">
        <h1><%= @category.title %></h1>
        <%= render 'tags_list', tags: @tags %>
    </div>
    <hr class="green"><hr class="gray">
<% end %>
<% content_for :articles_content do %>
    <div id="news-list">
        <% @articles.each do |article| %>
            <%= render 'article_item', article: article %>
        <% end %>
    </div>
    <div class="pagination">
        <%= paginate @articles %>
    </div>
<% end %>

app/views/articles/recent.js.erb
$('#side-feed-content').html('<%= j render @feed_articles %>');

app/views/articles/search.html.erb
<% content_for :articles_header do %>
    <%= render 'searchbox' %>
    <h2><%= params[:query] %></h2>
    <p>Найдено результатов: <%= @count %></p>
<% end %>
<% content_for :articles_content do %>
    <div id="search-list">
        <% @articles.each do |article| %>
            <%= render 'article_item', article: article %>
        <% end %>
    </div>
    <div class="pagination">
        <%= paginate @articles %>
    </div>
<% end %>

app/views/articles/show.html.erb
<% content_for :articles_header do %>
    <div class="date">
        <%= format_datetime(@article.published_at) %>
    </div>
    <h1><%= @article.title %></h1>
    <hr class="green"><hr class="gray">
<% end %>
<% content_for :articles_content do %>
    <div id="article">
        <div class="stats">
            <img src="https://tengrinews.kz/tengri_new/img/circle-viewings.svg">
            <span><%= @article.views %></span>
            <%# Views & comms count & share %>
        </div>
        <div class="picture">
            <picture>
                <%# Picture %>
                <img class="main-news_top_item_img" loading="lazy" src="<%= @article.image_url %>
" alt="Фото: МЧС">
            </picture>
            <span><%= @article.thumb_caption %></span>
        </div>
        <div class="text">
            <h4><%= @article.tldr %></h4>
            <hr>
            <div id="article-text">
                <%# content %>
                <%= raw(@article.content) %>
            </div>
        </div>
    </div>
<% end %>

app/views/articles/tags.html.erb
<% content_for :articles_header do %>
    <div class="breadcrumb">
        <%= link_to "Главная |", "/" %> <%= @tag.name %>
    </div>
    <div class="title">
        <h1><%= @tag.name %></h1>
        <%= render 'tags_list', tags: @tags %>
    </div>
    <hr class="green"><hr class="gray">
<% end %>
<% content_for :articles_content do %>
    <div id="tag-articles-list">
        <% @articles.each do |article| %>
            <%= render 'article_item', article: article %>
        <% end %>
    </div>
    <div class="pagination">
        <%= paginate @articles %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <div class="container">
        <nav class="border">
            <a href="/">
                <img src="https://tengrinews.kz/tengri_new/img/tengri-news.svg
" alt="TengriNews">
            </a><a href="/">
                <img src="https://tengrinews.kz/tengri_new/img/tengri-news.svg
" alt="TengriNews">
            </a>
        </nav>
        <div class="tags border">
            <%# items sized to 1/6 and flex %>
        </div>
        <div class="contacts border">
            <nav>
                <%# link_to %>
            </nav>
            <div class="departments">
                <%# departments %>
                <div class="department">
                    <span>Name</span>
                    <img src="https://tengrinews.kz/tengri_new/img/phone.svg" alt="WhatsApp">
                    <a href="https://api.whatsapp.com/send?phone=77770014499&text=%20">
                        +7 (777) 001 44 99
                    </a>
                </div>
            </div>
            <div class="social">
                <%# items %>
                <a href="">
                    <img src="" alt="Social media link">
                </a>
            </div>
        </div>
        <div class="bottom">
            <div class="left">
                <span>© 2008-2024 ТОО «EML»</span>
                <img src="https://tengrinews.kz/edu/img/18+.svg">
                <a href="https://tengrinews.kz/page/information/">Правила использования материалов</a>
                <a href="https://tengrinews.kz/page/confidential/">Политика конфиденциальности</a>
            </div>
            <div class="right">
                <span>Скачать наше приложение</span>
                <a href="https://apps.apple.com/kz/app/tengrinews-for-iphone/id510927516">
                    <img src="https://tengrinews.kz/edu/img/app_ios.svg">
                </a>
                <a href="https://play.google.com/store/apps/details?id=kz.tengrinews&amp;pli=1">
                    <img src="https://tengrinews.kz/edu/img/app_android.svg">
                </a>
                <a href="https://appgallery.huawei.com/app/C101462841?sharePrepath=ag&amp;locale=ru_RU&amp;source=appshare&amp;subsource=C101462841">
                    <img src="https://tengrinews.kz/edu/img/app_huawei.svg">
                </a>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header id="top">
    <div class="container">
        <nav>
            <a href="">NEWS</a>
            <a href="">NEWS2</a>
        </nav>
        <a href="https://tengrinews.kz/page/contact/">
            Редакция
            <img src="https://tengrinews.kz/tengri_new/img/phone.svg"> +7 (777) 001 44 99
        </a>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>TengriClone</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
        <%= javascript_importmap_tags %>
        <%= turbo_refreshes_with method: :morph, scroll: :preserve %>
        <%= yield :stylesheets %>
        <%= yield :metatags %>
    </head>
    <body>
        <%= render 'layouts/header' %>
        <%= content_for?(:main_content) ? yield(:main_content) : yield %>
        <!--<div class="notice"><%= notice %></div>
        <div class="alert"><%= alert %></div>-->
        <%= render 'layouts/footer' %>
        <%= yield :scripts %>
    </body>
</html>

app/views/layouts/articles.html.erb
<% content_for :main_content do %>
    <header id="articles" class="container">
        <div class="menu bg-white">
            <div class="left">
                <div class="burger">
                    <div></div>
                </div>
                <a href="/">
                    <img src="https://tengrinews.kz/tengri_new/img/logo.svg" alt="TengriNews Logo">
                </a>
                <nav>
                    <%= link_to "Новости", news_category_path %>
                    <%= link_to "Статьи", articles_category_path %>
                    <%# <a href="/">Что будет с Казахстаном?</a> %>
                </nav>
            </div>
            <div class="right">
                <button>
                    <img src="https://tengrinews.kz/tengri_new/img/menu-lang.svg" alt="Language Switch">
                </button>
                <button id="search-button">
                    <img src="https://tengrinews.kz/tengri_new/img/menu-search.svg" alt="Search">
                </button>
            </div>
        </div>
        <a class="wp_link" href="https://whatsapp.com/channel/0029VaC8d1M3AzNVm4DlYk2H">
            <div>Подписывайтесь на канал Tengrinews.kz в WhatsApp</div>
            <img src="https://tengrinews.kz/tengri_new/img/urgent-button.svg" alt="Button">
        </a>
        <div id="search-container">
            <%= render 'searchbox' %>
        </div>
    </header>
    <div id="articles-layout" class="row container bg-white">
        <div id="articles-header">
            <%= yield(:articles_header) %>
        </div>
        <div id="articles-content">
            <%= content_for?(:articles_content) ? yield(:articles_content) : yield %>
        </div>
        <div id="side-feed">
            <%= sort_link(column: "published_at", label: "Последние", active:true) %>
            <%= sort_link(column: "views", label: "Популярные") %>
            <div id="side-feed-content">
                <%= turbo_frame_tag "feed", src: feed_articles_path(column: "published_at", direction: "desc") do %>
                <% end %>
            </div>
        </div>
    </div>
<% end %>
<% content_for :stylesheets do %>
    <%= stylesheet_link_tag "articles", "data-turbo-track": "reload" %>
<% end %>
<% content_for :scripts do %>
    <%= javascript_include_tag "feed", "search", "data-turbo-track": "reload" %>
<% end %>
<%= render template: 'layouts/application' %>